# Generated by Django 3.2.4 on 2021-06-04 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, verbose_name='Короткое название')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адресс')),
                ('cost_per_night', models.FloatField(blank=True, default=None, null=True, verbose_name='Стоимость за ночь')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квариры',
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField(verbose_name='Начало')),
                ('end', models.DateField(verbose_name='Конец')),
                ('cost_per_night', models.FloatField(blank=True, default=None, null=True, verbose_name='Цена за ночь')),
                ('paid', models.FloatField(blank=True, default=None, null=True, verbose_name='Заплачено')),
                ('deposit', models.FloatField(blank=True, default=None, null=True, verbose_name='Залог')),
                ('total_cost', models.FloatField(blank=True, default=None, null=True, verbose_name='Полная стоимость')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('flat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rents.flat', verbose_name='Квартира')),
                ('tenant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant', verbose_name='Съемщик')),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
            },
        ),
    ]
