# Generated by Django 3.2.4 on 2021-06-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-id'], 'verbose_name': 'Съемщик', 'verbose_name_plural': 'Съемщики'},
        ),
    ]
