# Generated by Django 3.2 on 2021-05-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pin',
            name='phone',
            field=models.CharField(db_index=True, max_length=13, primary_key=True, serialize=False, unique=True),
        ),
    ]
