# Generated by Django 3.2 on 2021-05-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210518_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('ru-RU', 'Русский'), ('en-US', 'Английский'), ('en-UK', 'Английский (Великобритания)')], default='ru-RU', max_length=100, verbose_name='Язык'),
        ),
    ]
