# Generated by Django 3.2.4 on 2021-06-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_locale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appleaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='googleaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='points_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.DeleteModel(
            name='AppleAccount',
        ),
        migrations.DeleteModel(
            name='GoogleAccount',
        ),
    ]
