# Generated by Django 3.2.4 on 2021-06-04 17:14

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, unique=True, validators=[authentication.validators.validate_phone], verbose_name='Номер телефона'),
        ),
    ]
