# Generated by Django 3.2.4 on 2021-06-11 15:50

import authentication.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('active', models.BooleanField(default=True, verbose_name='Активная')),
            ],
            options={
                'verbose_name': 'Почта',
                'verbose_name_plural': 'Почта для рассылки',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[authentication.validators.validate_phone], verbose_name='Номер телефона'),
        ),
    ]
